include:
  - template: Security/SAST.gitlab-ci.yml

.go-cache:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.20
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - lint
  - test
  - build
  - release

lint:
  extends: ".go-cache"
  stage: lint
  script:
    - go vet $(go list ./... | grep -v /vendor/)

test:
  extends: ".go-cache"
  stage: test
  script:
    - go install
    - go test ./... -coverprofile=coverage.txt -covermode count
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

sast:
  stage: test

build:
  extends: ".go-cache"
  stage: build
  script:
    - mkdir -p bin
    - go build -o bin ./...
  artifacts:
    paths:
      - bin

.release:
  extends: ".go-cache"
  stage: release
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/goreleaser/goreleaser:latest
    entrypoint: ['']
  only:
    - tags
  variables:
    GIT_DEPTH: 0
  script:
    - GOVERSION=$(go version) goreleaser release --clean

release-gitlab:
  extends: ".release"
  before_script:
    - unset GITHUB_TOKEN

