before:
  hooks:
    - 'go mod tidy'

builds:
  - env:
      - 'CGO_ENABLED=0'
    goos:
      - 'linux'
      - 'freebsd'
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goversion={{.Env.GOVERSION}}"
archives:
  - replacements:
      linux: 'linux'
      386: 'i386'
      amd64: 'x86_64'
    files:
      - 'LICENSE'
      - 'README.md'
      - src: '.pkg'
        dst: 'config'
        strip_parent: true

    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - homepage: 'https://node-3.net/zander'
    maintainer: 'Nick Adams <zander@node-3.net>'
    description: |-
      Software to manage dedicated doom server instances
    license: 'MIT'
    formats:
      - 'deb'
      - 'rpm'
      - 'archlinux'
    contents:
      - src: '.pkg/zander.service'
        dst: '/lib/systemd/system/zander.service'
      - src: '.pkg/zander.toml'
        dst: '/etc/xdg/zander/zander.toml'
        type: 'config|noreplace'
      - src: '.pkg/zander.toml'
        dst: '/usr/share/zander/zander.toml'
      - src: '.pkg/servers/doom2.toml'
        dst: '/usr/share/zander/servers/doom2.toml'
      - dst: '/etc/xdg/zander/servers'
        type: 'dir'
        file_info:
          mode: 0755

gitlab_urls:
  api: 'https://gitlab.node-3.net/api/v4/'
  download: 'https://gitlab.node-3.net'
  skip_tls_verify: false
  use_package_registry: false

aurs:
  - name: 'zander-bin'
    homepage: 'https://node-3.net/zander'
    description: 'Software to manage dedicated doom server instances'
    maintainers:
      - 'Nick Adams <zander at node-3.net>'
    license: 'MIT'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/zander-bin.git'
    skip_upload: false
    package: |-
      # bin
      install -Dm755 "zander_${pkgver}_linux_${CARCH}/zander" "${pkgdir}/usr/bin/zander"

      # license
      install -Dm644 "zander_${pkgver}_linux_${CARCH}/LICENSE" "${pkgdir}/usr/share/licenses/zander/LICENSE"

      # TODO: completions
    commit_author:
      name: 'Nick Adams'
      email: 'zander@node-3.net'
    url_template: 'https://gitlab.node-3.net/zander/zander/-/releases/{{ .Tag }}/downloads/{{ .ArtifactName }}'
