// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: zproto/server.proto

package zproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZanderClient is the client API for Zander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZanderClient interface {
	ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error)
	Attach(ctx context.Context, opts ...grpc.CallOption) (Zander_AttachClient, error)
}

type zanderClient struct {
	cc grpc.ClientConnInterface
}

func NewZanderClient(cc grpc.ClientConnInterface) ZanderClient {
	return &zanderClient{cc}
}

func (c *zanderClient) ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error) {
	out := new(ListServersResponse)
	err := c.cc.Invoke(ctx, "/zproto.Zander/ListServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zanderClient) Attach(ctx context.Context, opts ...grpc.CallOption) (Zander_AttachClient, error) {
	stream, err := c.cc.NewStream(ctx, &Zander_ServiceDesc.Streams[0], "/zproto.Zander/Attach", opts...)
	if err != nil {
		return nil, err
	}
	x := &zanderAttachClient{stream}
	return x, nil
}

type Zander_AttachClient interface {
	Send(*AttachIn) error
	Recv() (*AttachOut, error)
	grpc.ClientStream
}

type zanderAttachClient struct {
	grpc.ClientStream
}

func (x *zanderAttachClient) Send(m *AttachIn) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zanderAttachClient) Recv() (*AttachOut, error) {
	m := new(AttachOut)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ZanderServer is the server API for Zander service.
// All implementations must embed UnimplementedZanderServer
// for forward compatibility
type ZanderServer interface {
	ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error)
	Attach(Zander_AttachServer) error
	mustEmbedUnimplementedZanderServer()
}

// UnimplementedZanderServer must be embedded to have forward compatible implementations.
type UnimplementedZanderServer struct {
}

func (UnimplementedZanderServer) ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedZanderServer) Attach(Zander_AttachServer) error {
	return status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedZanderServer) mustEmbedUnimplementedZanderServer() {}

// UnsafeZanderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZanderServer will
// result in compilation errors.
type UnsafeZanderServer interface {
	mustEmbedUnimplementedZanderServer()
}

func RegisterZanderServer(s grpc.ServiceRegistrar, srv ZanderServer) {
	s.RegisterService(&Zander_ServiceDesc, srv)
}

func _Zander_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZanderServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zproto.Zander/ListServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZanderServer).ListServers(ctx, req.(*ListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zander_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZanderServer).Attach(&zanderAttachServer{stream})
}

type Zander_AttachServer interface {
	Send(*AttachOut) error
	Recv() (*AttachIn, error)
	grpc.ServerStream
}

type zanderAttachServer struct {
	grpc.ServerStream
}

func (x *zanderAttachServer) Send(m *AttachOut) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zanderAttachServer) Recv() (*AttachIn, error) {
	m := new(AttachIn)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Zander_ServiceDesc is the grpc.ServiceDesc for Zander service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zander_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zproto.Zander",
	HandlerType: (*ZanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServers",
			Handler:    _Zander_ListServers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _Zander_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zproto/server.proto",
}
